/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HidatoGUI.java
 *
 * Created on 21-Dec-2009, 04:35:11
 */
package biz.karms.hidato.view.swing;

import biz.karms.hidato.app.util.impl.GameVariantImpl;
import biz.karms.hidato.app.util.impl.HidatoConstraint;
import com.masprop.cluster1.shared.model.Constraint;
import com.masprop.cluster1.shared.model.GameLevelType;
import com.masprop.cluster1.shared.model.GameType;
import com.masprop.cluster1.shared.model.GameVariant;
import com.masprop.cluster1.shared.view.GUI;
import com.masprop.cluster1.shared.view.GUIManager;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author Karm
 */
public class HidatoGUI extends GUI {

    private JFrame wizFrame = null;

    public HidatoGUI(GUIManager guiManager) {
        setGuiManager(guiManager);
        guiManager.setGui(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wizPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xDimensionSpinner = new javax.swing.JSpinner();
        yDimensionSpinner = new javax.swing.JSpinner();
        gameLevelComboBox = new javax.swing.JComboBox();
        boardShapeComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        statPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statPanelContainer = new javax.swing.JPanel();
        dismissStatsButton = new javax.swing.JButton();

        jLabel1.setText("X dimension");

        jLabel2.setText("Y dimension");

        jLabel3.setText("Game level");

        jLabel4.setText("Board shape");

        xDimensionSpinner.setModel(new javax.swing.SpinnerNumberModel(6, 4, 20, 1));
        xDimensionSpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xDimensionSpinnerMouseClicked(evt);
            }
        });
        xDimensionSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xDimensionSpinnerStateChanged(evt);
            }
        });

        yDimensionSpinner.setModel(new javax.swing.SpinnerNumberModel(6, 4, 20, 1));
        yDimensionSpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yDimensionSpinnerMouseClicked(evt);
            }
        });
        yDimensionSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yDimensionSpinnerStateChanged(evt);
            }
        });

        gameLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Test", "Easy", "Medium", "Difficult" }));
        gameLevelComboBox.setToolTipText("Game level means how many cells are empty for you to fill. Test generates complete game.");

        boardShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rectangular" }));

        jButton1.setText("Dismiss");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wizPanelLayout = new javax.swing.GroupLayout(wizPanel);
        wizPanel.setLayout(wizPanelLayout);
        wizPanelLayout.setHorizontalGroup(
            wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizPanelLayout.createSequentialGroup()
                .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wizPanelLayout.createSequentialGroup()
                        .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yDimensionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xDimensionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wizPanelLayout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wizPanelLayout.createSequentialGroup()
                            .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boardShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gameLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        wizPanelLayout.setVerticalGroup(
            wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizPanelLayout.createSequentialGroup()
                .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xDimensionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yDimensionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gameLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boardShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(wizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        statPanelContainer.setLayout(new java.awt.GridLayout(1, 2));
        jScrollPane1.setViewportView(statPanelContainer);

        dismissStatsButton.setText("Dismiss");
        dismissStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissStatsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statPanelLayout = new javax.swing.GroupLayout(statPanel);
        statPanel.setLayout(statPanelLayout);
        statPanelLayout.setHorizontalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dismissStatsButton))
        );
        statPanelLayout.setVerticalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dismissStatsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wizFrame.setVisible(false);
        this.setEnabled(true);
        this.validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int numberOfCellsAlreadyFilled = 0;

        GameLevelType gameLevelType = null;
        if (gameLevelComboBox.getSelectedItem().toString().equalsIgnoreCase("easy")) {
            gameLevelType = GameLevelType.EASY;
        } else if (gameLevelComboBox.getSelectedItem().toString().equalsIgnoreCase("medium")) {
            gameLevelType = GameLevelType.MEDIUM;
        } else if (gameLevelComboBox.getSelectedItem().toString().equalsIgnoreCase("difficult")) {
            gameLevelType = GameLevelType.DIFFICULT;
        } else if (gameLevelComboBox.getSelectedItem().toString().equalsIgnoreCase("test")) {
            gameLevelType = GameLevelType.EASY;
            numberOfCellsAlreadyFilled = (int) (Integer) xDimensionSpinner.getValue() * (int) (Integer) yDimensionSpinner.getValue();
        } else {
            throw new IllegalArgumentException("Unsupported GameLevel");
        }
        GameVariant gameVariant = null;
        if (boardShapeComboBox.getSelectedItem().toString().equalsIgnoreCase("rectangular")) {
            gameVariant = GameVariantImpl.RECTANGULAR_SHAPE;
        } else if (boardShapeComboBox.getSelectedItem().toString().equalsIgnoreCase("oval")) {
            gameVariant = GameVariantImpl.OVAL_SHAPE;
        } else if (boardShapeComboBox.getSelectedItem().toString().equalsIgnoreCase("donut")) {
            gameVariant = GameVariantImpl.DONUT_SHAPE;
        } else {
            throw new IllegalArgumentException("Unsupported GameLevel");
        }
        Constraint constraint = new HidatoConstraint(
                gameLevelType,
                gameVariant,
                numberOfCellsAlreadyFilled,
                GameType.HIDATO,
                (Integer) xDimensionSpinner.getValue(),
                (Integer) yDimensionSpinner.getValue());
        getGuiManager().getNewGame(constraint);
        wizFrame.setVisible(false);
        this.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void xDimensionSpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xDimensionSpinnerMouseClicked
    }//GEN-LAST:event_xDimensionSpinnerMouseClicked

    private void yDimensionSpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yDimensionSpinnerMouseClicked
    }//GEN-LAST:event_yDimensionSpinnerMouseClicked

    private void xDimensionSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xDimensionSpinnerStateChanged
        if ((Integer) xDimensionSpinner.getValue() > (Integer) yDimensionSpinner.getValue() + 4) {

            yDimensionSpinner.setValue(new Integer((Integer) yDimensionSpinner.getValue() + 1));
        }
        if ((Integer) xDimensionSpinner.getValue() + 4 < (Integer) yDimensionSpinner.getValue()) {
            yDimensionSpinner.setValue(new Integer((Integer) yDimensionSpinner.getValue() - 1));
        }
    }//GEN-LAST:event_xDimensionSpinnerStateChanged

    private void yDimensionSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yDimensionSpinnerStateChanged
        if ((Integer) yDimensionSpinner.getValue() > (Integer) xDimensionSpinner.getValue() + 4) {

            xDimensionSpinner.setValue(new Integer((Integer) xDimensionSpinner.getValue() + 1));
        }
        if ((Integer) yDimensionSpinner.getValue() + 4 < (Integer) xDimensionSpinner.getValue()) {
            xDimensionSpinner.setValue(new Integer((Integer) xDimensionSpinner.getValue() - 1));
        }
    }//GEN-LAST:event_yDimensionSpinnerStateChanged

    private void dismissStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissStatsButtonActionPerformed
       ((HidatoGUIManager)getGuiManager()).closeStatisctic();
    }//GEN-LAST:event_dismissStatsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boardShapeComboBox;
    private javax.swing.JButton dismissStatsButton;
    private javax.swing.JComboBox gameLevelComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel statPanel;
    private javax.swing.JPanel statPanelContainer;
    private javax.swing.JPanel wizPanel;
    private javax.swing.JSpinner xDimensionSpinner;
    private javax.swing.JSpinner yDimensionSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void newGameMenuItemActionPerformed(ActionEvent evt) {
        wizFrame = new JFrame("Preferencies");
        wizFrame.setBounds(200, 200, 240, 200);
        wizFrame.add(wizPanel);
        this.setEnabled(false);
        this.validate();
        wizFrame.setVisible(true);
        wizPanel.validate();
        wizFrame.validate();
    }

    public void manualMenuItemActionPerformed()
    {
        JFrame helpFrame = new JFrame();
        Container content = helpFrame.getContentPane();

        JEditorPane helpEditorPane = new JEditorPane();
        helpEditorPane.setEditable(false);

        JScrollPane helpScrollPane = new JScrollPane(helpEditorPane);
        content.add(helpScrollPane);

        helpFrame.setTitle("Hidato Manual");
        helpFrame.setSize(640, 480);
        helpFrame.setMinimumSize(new Dimension(400, 500));


        try {
            InputStream helpIns = getClass().getResourceAsStream("resources/help.html");
            helpEditorPane.setEditorKit(new HTMLEditorKit());
            helpEditorPane.read(helpIns, null);
        } catch (IOException ex) {
              helpEditorPane.setContentType("text/html");
              helpEditorPane.setText("<html>Could not load resources/help.html </html>");
        }
        helpFrame.setVisible(true);
    }

    public JPanel getStatPanelContainer() {
        return statPanelContainer;
    }

    public JPanel getStatPanel() {
        return statPanel;
    }
    
}
