/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HidatoGUI.java
 *
 * Created on 26-Oct-2009, 18:46:30
 */

package biz.karms.hidato.view.swing;

import biz.karms.hidato.app.controller.impl.HidatoGameManager;
import biz.karms.hidato.app.game.impl.HidatoGame;
import biz.karms.hidato.app.game.matrix.impl.HidatoMatrix;

/**
 *
 * @author Karm
 */
public class HidatoGUI extends javax.swing.JFrame {

    /** Creates new form HidatoGUI */
    public HidatoGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HidatoGUI().setVisible(true);
            }
        });*/
        
        HidatoGameManager hgm = new HidatoGameManager();

        HidatoGame hg = (HidatoGame) hgm.getNewGame(null);
        ((HidatoMatrix) hg.getGameMatrix()).write();

        System.out.println();

        hg = (HidatoGame) hgm.solveGame(hg);
        ((HidatoMatrix) hg.getGameMatrix()).write();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
